version: '3'

services:
  gateway:
    container_name: gateway
    restart: always
    build: ./gateway
    ports:
      - "8000:8000"

  characters:
    container_name: characters
    restart: always
    build: ./characters
    expose:
      - "8001"

  films:
    container_name: films
    restart: always
    build: ./films
    expose:
      - "8002"

  planets:
    container_name: planets
    restart: always
    build: ./planets
    expose:
      - "8003"

  database:
    container_name: database
    restart: always
    build: ./database
    expose:
      - "8004"